import Head from 'next/head'
import Link from 'next/link'
import { useMoralis } from 'react-moralis'
import Image from 'next/image'
import Nav from '../components/nav'
import CopyURL from '../components/copyurl'

function Home() {
  const { isAuthenticated, user} = useMoralis()

  return (
    <div 
    className={`flex flex-col h-screen justify-between ${
      !isAuthenticated && "bg-login bg-cover bg-center overflow-hidden"
    }`}
  >
      <Head>
        <title>CalenderME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Nav isAuthenticated={isAuthenticated}/>

      <main className="">
       
        <div className="flex flex-col items-center justify-center py-2">
          {isAuthenticated ? (
            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
              <Link href="/me">
                <button className="button__box !mt-20">My Meetings</button>

              </Link>
              <div className="font-bold pt-48 pb-2 underline decoration-8 decoration-[#B4AAD0]">
              My invite URL: localhost:3000/{user.get("ethAddress")}
              </div>
              <CopyURL/>
            </main>
          ):(
            <div className="login__shadow absolute bottom-1/2 text-3xl text-white font-bold">
            
            please login
          </div>
          )}
        </div>
      </main>
      {/* <main className="mb-auto h-10 bg-green-500"> main</main> */}
      <footer className="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 h-10 ">
      <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400"> © 2022  built For <a href="https://ethcchack.com/" class="hover:underline">Ethcc™</a>. 
    </span>
  
    
         <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by IPFS and Moralis{' '}
          
        </a>
      </footer>


      
    </div>
  )
}

export default Home;