import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useMoralis } from 'react-moralis'
import Image from 'next/image'
import Nav from '../components/nav'

function Home() {
  const { isAuthenticated, user} = useMoralis()

  return (
    <div className={styles.container}>
      <Head>
        <title>BookME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Nav isAuthenticated={isAuthenticated}/>

      <main className={styles.main}>
       
        <div className="flex flex-col items-center justify-center py-2">
          {isAuthenticated ? (
            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
              <Link href="/me">
                <button className="button__box !mt-20">My Meetings</button>

              </Link>
              <div className="font-bold pt-48 pb-2 underline decoration-8 decoration-[#B4AAD0]">
              My invite URL: localhost:3000/{user.get("ethAddress")}
              </div>
              <div></div>
            </main>
          ):(
            <div className="login__shadow absolute bottom-1/2 text-3xl text-white font-bold">
            
            please login
          </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;